# Generated by Django 2.0 on 2018-01-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='device_type',
            field=models.CharField(choices=[('TA', 'Tablet'), ('PH', 'Smartphone')], default='PH', max_length=2),
        ),
    ]
